multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: jaco_kinematic_chain
    base_link: jaco_base_link
    tip_link: jaco_hand_link
default_collision_operations:
  - object1: base_link
    object2: jaco_base_link
    operation: disable  # Adjacent in collision
  - object1: jaco_base_link
    object2: jaco_shoulder_link
    operation: disable  # Adjacent in collision
  - object1: jaco_shoulder_link
    object2: jaco_upper_arm_link
    operation: disable  # Adjacent in collision
  - object1: jaco_upper_arm_link
    object2: jaco_lower_arm_link
    operation: disable  # Adjacent in collision
  - object1: jaco_lower_arm_link
    object2: jaco_lower_arm_roll_link
    operation: disable  # Adjacent in collision
  - object1: jaco_lower_arm_roll_link
    object2: jaco_wrist_link
    operation: disable  # Adjacent in collision
  - object1: jaco_wrist_link
    object2: jaco_hand_link
    operation: disable  # Adjacent in collision
  - object1: jaco_hand_link
    object2: jaco_finger_1_link
    operation: disable  # Adjacent in collision
  - object1: jaco_hand_link
    object2: jaco_finger_2_link
    operation: disable  # Adjacent in collision
  - object1: jaco_hand_link
    object2: jaco_finger_3_link
    operation: disable  # Adjacent in collision
  - object1: jaco_finger_1_link
    object2: jaco_finger_3_link
    operation: disable  # Never in collision