<?xml version="1.0"?>
<robot 
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <include filename="$(find jaco_description)/urdf/common.xacro" />

    <property name="base_length" value="0.2"/>
    <property name="base_radius" value="0.05"/>
    <property name="shoulder_radius" value="0.05"/>
    <property name="upper_arm_length" value="0.4"/>
    <property name="upper_arm_radius" value="0.025"/>
    <property name="elbow_radius" value="0.05"/>
    <property name="lower_arm_length" value="0.20"/>
    <property name="lower_arm_radius" value="0.025"/>
    <property name="wrist_length" value="0.10"/>
    <property name="wrist_radius" value="0.025"/>

    <xacro:macro name="jaco_arm_v0" params="name parent">

      <joint name="${name}_base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="${parent}"/>
        <child link="${name}_base_link"/>
      </joint>
      <link name="${name}_base_link">
        <visual>
          <origin xyz="0 0 ${base_length/2}"/>
          <geometry>
            <cylinder length="${base_length}" radius="${base_radius}"/>
          </geometry>
        </visual>
      </link>

      <joint name="${name}_shoulder_yaw_joint" type="revolute">
        <origin xyz="0 0 ${base_length}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="${name}_base_link"/>
        <child link="${name}_shoulder_link"/>
        <limit lower="${-M_PI}" upper="${M_PI}" effort="1" velocity="${M_PI}"/>
      </joint>
      <link name="${name}_shoulder_link">
        <visual>
          <geometry>
            <sphere radius="${shoulder_radius}"/>
          </geometry>
        </visual>
      </link>
      
      <joint name="${name}_shoulder_pitch_joint" type="revolute">
        <origin xyz="0 0 ${shoulder_radius}" rpy="${M_PI/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="${name}_shoulder_link"/>
        <child link="${name}_upper_arm_link"/>
        <limit lower="${-M_PI}" upper="${M_PI}" effort="1" velocity="${M_PI}"/>
      </joint>
      <link name="${name}_upper_arm_link">
        <visual>
          <origin xyz="${upper_arm_length/2} 0 0" rpy="0 ${M_PI/2} 0"/>
          <geometry>
            <cylinder length="${upper_arm_length}" radius="${upper_arm_radius}"/>
          </geometry>
        </visual>
      </link>

      <joint name="${name}_elbow_pitch_joint" type="revolute">
        <origin xyz="${upper_arm_length} 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="${name}_upper_arm_link"/>
        <child link="${name}_lower_arm_link"/>
        <limit lower="${-M_PI}" upper="${M_PI}" effort="1" velocity="${M_PI}"/>
      </joint>
      <link name="${name}_lower_arm_link">
        <visual>
            <origin xyz="0 ${lower_arm_length/2} 0" rpy="${-M_PI/2} 0 0"/>
          <geometry>
            <cylinder length="${lower_arm_length}" radius="${lower_arm_radius}"/>
          </geometry>
        </visual>
      </link>
      <joint name="${name}_elbow_roll_joint" type="revolute">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="${name}_lower_arm_link"/>
        <child link="${name}_lower_arm_roll_link"/>
        <limit lower="${-M_PI}" upper="${M_PI}" effort="1" velocity="${M_PI}"/>
      </joint>
      <link name="${name}_lower_arm_roll_link">
        <visual>
          <geometry>
            <sphere radius="${elbow_radius}"/>
          </geometry>
        </visual>
      </link>
      <joint name="${name}_wrist_roll_joint" type="revolute">
        <origin xyz="0 ${wrist_length/2} ${lower_arm_length}" rpy="${-M_PI/4} 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="${name}_lower_arm_roll_link"/>
        <child link="${name}_wrist_link"/>
        <limit lower="${-M_PI}" upper="${M_PI}" effort="1" velocity="${M_PI}"/>
      </joint>
      <link name="${name}_wrist_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <cylinder length="${wrist_length/2}" radius="${wrist_radius}"/>
          </geometry>
        </visual>
      </link>
      <joint name="${name}_hand_roll_joint" type="revolute">
        <origin xyz="0 0 ${wrist_length/2}" rpy="${M_PI/4} 0 0"/>
        <axis xyz="0 0 1"/>
        <parent link="${name}_wrist_link"/>
        <child link="${name}_hand_link"/>
        <limit lower="${-M_PI}" upper="${M_PI}" effort="1" velocity="${M_PI}"/>
      </joint>
      <link name="${name}_hand_link">
        <visual>
            <origin xyz="0 0 ${wrist_length/4}" rpy="0 0 0"/>
          <geometry>
            <cylinder length="${wrist_length/2}" radius="${wrist_radius}"/>
          </geometry>
        </visual>
      </link>


    </xacro:macro>
</robot>

